# `null` will be read as NoneType

# Model Parameters
model: null
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 8
spec_mask_len: 400
formula: True
formula_max_padding: 15
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
data: 
vocab_formula: 
vocab_smiles: 
dataset_mode: #!!!
split_testdata: True
aug_mode: null # Data Augmentation
testset_aug: null # Data Augmentation of test set
aug_num: 
smi_aug_num: 
max_shift: 
theta: 
alpha: 

# Train Parameters
save_path: 
batch_size: 128
num_epochs: 200
base_lr: 1.0
warmup_steps: 3000
Resume: False
test_train: False
seed: 3234

earlystop_delta: 0.08
earlystop_patience: 5
report_step: 40
check_point_step: 20
