# `null` will be read as NoneType

# Model Parameters
model: null
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 8
spec_mask_len: 400
formula: True
formula_max_padding: 15
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
test_data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/modified_ViT/30data.pkl
vocab_formula: null
vocab_smiles: null

# Translate Parameters
save_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/test_workflow
batch_size: 128
seed: 3234
translate_mode: B # G:Greedy Search or B: Beam Search
beam_width: 10
n_best: 10
testInf: False # If True, only translate 10 batches
