# `null` will be read as NoneType

# Model Parameters
fix_encoder: 
fix_decoder: 
formula: True
formula_max_padding: 15
spec_model: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/1with_smiles_model/encoder_srcpad215/train/model/best_model_optimizer_params.tar
smi_model: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/1with_smiles_model/smiles_model_srcpad40/model/best_model_optimizer_params.tar
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 16
spec_mask_len: 200
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/modified_ViT/30data.pkl
vocab_formula: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/ps8_bs128_EmbedPatchAttention/vocab/vocab_formula.pt
vocab_smiles: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/ps8_bs128_EmbedPatchAttention/vocab/vocab_smiles.pt
aug_mode: null # Data Augmentation
testset_aug: null # Data Augmentation of test set

# Train Parameters
save_path: ./
batch_size: 128
num_epochs: 200
accum_iter: 10
base_lr: 1.0
warmup_steps: 3000
Resume: False
test_train: False
seed: 3234

earlystop_delta: 0.08
earlystop_patience: 5
