# Model Parameters
model: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/spec_2_smi/check_final_code/check_result/train/model/best_model_optimizer_params.tar
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 64
spec_mask_len: 50
formula: True
formula_max_padding: 15
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
test_data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/spec_2_smi/check_final_code/check_result/train/data/test_set.pt
vocab_formula: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/spec_2_smi/check_final_code/check_result/train/vocab/vocab_formula.pt
vocab_smiles: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/spec_2_smi/check_final_code/check_result/train/vocab/vocab_smiles.pt

# Translate Parameters
save_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/spec_2_smi/check_final_code/check_result/inf
batch_size: 512
seed: 3234
beam_width: 10
n_best: 10
testInf: False # If True, only run inference for 10 batches
