# `null` will be read as NoneType

# Model Parameters
model: null
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 64
spec_mask_len: 50
formula: True
formula_max_padding: 15
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/2data_aug/sameTrainDataset/noise_smiles/train2/data
vocab_formula: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/ps8_bs128_EmbedPatchAttention/train1/vocab/vocab_formula.pt
vocab_smiles: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/ps8_bs128_EmbedPatchAttention/train1/vocab/vocab_smiles.pt
split_testdata: False
dataset_mode:
aug_mode: # Data Augmentation
- verticalNoise 
- SMILES
testset_aug:  # Data Augmentation of test set
aug_num: 2
smi_aug_num: 1
max_shift: 
theta: 0.01
alpha: 5
split_testdata: False


# Train Parameters
save_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/2data_aug/sameTrainDataset/noise_smiles/train3
batch_size: 256
num_epochs: 200
base_lr: 1.0
warmup_steps: 3000
Resume: False
test_train: False
seed: 3234

earlystop_delta: 0.03
earlystop_patience: 5
report_step: 500
check_point_step: 1

