# `null` will be read as NoneType

# Model Parameters
model: null
src_max_padding: 415
tgt_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/modified_ViT/30data.pkl
vocab_smiles: null
num_newsmi: 5

# Train Parameters
save_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/test_workflow
batch_size: 128
num_epochs: 200
accum_iter: 10
base_lr: 1.0
warmup_steps: 3000
Resume: False
test_train: False
seed: 3234

earlystop_delta: 0.08
earlystop_patience: 5
