# `null` will be read as NoneType

# Model Parameters
model: null
src_max_pad: 415
tgt_max_pad: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
test_data: 
vocab_smiles: null

# Translate Parameters
save_path: 
batch_size: 512
seed: 3234
translate_mode: B # G:Greedy Search or B: Beam Search
beam_width: 10
n_best: 10
testInf: True # If True, only translate 10 batches
