# `null` will be read as NoneType

# Model Parameters
formula: True
formula_max_padding: 15
spec_model: null
smi_model: null
spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 8
spec_mask_len: 400
smiles_max_padding: 40
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
data: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/modified_ViT/30data.pkl
vocab_formula: null
vocab_smiles: null
aug_mode: null # Data Augmentation
testset_aug: null # Data Augmentation of test set

# Train Parameters
save_path: /rds/projects/c/chenlv-ai-and-chemistry/wuwj/FinalResult/0directly_train/withFormula/test_workflow
batch_size: 128
num_epochs: 200
accum_iter: 10
base_lr: 1.0
warmup_steps: 3000
Resume: False
test_train: False
seed: 3234

earlystop_delta: 0.08
earlystop_patience: 5
