# `null` will be read as NoneType

# Model Parameters
formula: True
formula_max_padding: 15
models: 
- /path/to/model_checkpoint_1
- /path/to/model_checkpoint_2
- /path/to/model_checkpoint_3


spec_embed: 'EmbedPatchAttention'
spec_len: 3200
patch_len: 64
spec_mask_len: 50
smiles_max_padding: 100
d_model: 512
num_heads: 8
layer_num: 4
d_ff: 2048
dropout: 0.1

# Data 
test_data: 
vocab_formula: 
vocab_smiles: 

# Translate Parameters
save_path: 
batch_size: 512
seed: 3234
beam_width: 10
n_best: 10
testInf: False # If True, only translate 10 batches
